name: automerge
on:
  workflow_run:
    workflows: ["build"]
    types: [completed]
    branches:
      - main
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.3
        with:
          label-name: "build"
          github-token: ${{ secrets.GITHUB_TOKEN }}
