name: automerge
on:
  pull_request:
    types:
      - labeled
    branches: [ "main" ]
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "plm9606/automerge_actions@1.2.3"
        with: 
          label-name: "build"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
