name: automerge
on:
  workflow_call
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: gitCheckOut
        uses: google-github-actions/setup-gcloud@v0
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
