name: Docker Image CI

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]

jobs:
  cd:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker build -t ${{ secrets.DOCKERHUB_REPO_MOYO }}
        docker push ${{ secrets.DOCKER_USERNAME }}
        
    - name: EC2 Docker Run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker rm -f $(docker ps -qa)
          docker rmi ${{ secrets.DOCKER_USERNAME }}/도커 레파지토리 이름
          docker pull ${{ secrets.DOCKER_USERNAME }}/도커 레파지토리 이름
          docker-compose up -d
