name: Docker Image CI

on:
  pull_request:
    types: [closed]
    branches: [ "main" ]

jobs:

  cd:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      working-directory: ./moyoserver
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_REPO: ${{ secrets.DOCKERHUB_REPO_MOYO }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    - name: Execute Gradle build
      run: ./gradlew bootJar
      working-directory: ${{ env.working-directory }}

    - name: Build the Docker image
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
        docker build -t $DOCKER_REPO .
        docker push $DOCKER_REPO
      working-directory: ${{ env.working-directory }}
        
    - name: EC2 Docker Run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull $DOCKER_REPO
            docker-compose up -d
            docker image prune -f
